### ISSUE TITLE
warning：python-Levenshtein

### ISSUE THREAD

**Issue by littleheary** [s0md3v/Bolt#6]
python3 bolt.py -h

     ⚡ BOLT  ⚡
    
/usr/local/lib/python3.7/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

i have install python-Levenshtein.
but the warning exists,too

**Comment by s0md3v** [comment]
install `python-levenshtein` with `pip3` not `pip`

**Comment by punk12321** [comment]
└──╼ $sudo python3 bolt.py -u https://github.com -l 2
[sudo] password for punk: 

     ⚡ BOLT  ⚡
    
Traceback (most recent call last):
  File "bolt.py", line 33, in <module>
    from core.entropy import isRandom
  File "/home/punk/Music/Bolt/core/entropy.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Is there any solution for this issue ?

**Comment by iNoSec** [comment]
Yeah dont spam other's issue...
