### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by punk12321** [s0md3v/Bolt#9]
└──╼ $sudo python3 bolt.py -u https://github.com -l 2
[sudo] password for punk:

 ⚡ BOLT  ⚡
Traceback (most recent call last):
File "bolt.py", line 33, in 
from core.entropy import isRandom
File "/home/punk/Music/Bolt/core/entropy.py", line 1, in 
import numpy as np
ModuleNotFoundError: No module named 'numpy'

Is there any solution for this issue ?

**Comment by iNoSec** [comment]
Did you try to install it??

**Comment by punk12321** [comment]
Thank yo @iNoSec 

I tried to install 
└──╼ $sudo pip install numpy; sudo pip3 install numpy
└──╼ $sudo pip install scipy; sudo pip3 install scipy

Issue is resolved :)
